Update README.md
aws-actions/configure-aws-credentials pull request #430
Opened 2022-04-26 22:53 UTC by liwadman

Added explicit language that this action is not supported on github currently.

*Issue #, if available:*

N/A

*Description of changes:*

I added clarifying language that says that the tagging with web identity tokens is not currently supported with github actions currently, as to not require customers to discover this themselves.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-05-25 17:09 UTC, RichardTMiles commented
Thanks, to everyone!

While your at it, as another community member, could you document this 
https://github.community/t/skip-output-aws-account-id-since-it-may-contain-secret/123791/9

 mask-aws-account-id: 'no'

2022-10-05 02:04 UTC, peterwoodworth commented
We currently have a check for this https://github.com/aws-actions/configure-aws-credentials/blob/5a4b8f03d1948e564e5e97d168d19dbbab75abf4/index.js#L89-L91

Are you running into a bug where this is occurring @liwadman?

2022-10-05 02:05 UTC, peterwoodworth requested changes
The limitation is on AWS's side I believe with OIDC tokens. Is there any documentation you've found which supports the statement you've added?

2022-10-07 19:28 UTC, peterwoodworth requested changes
Thanks for linking me documentation to the [right page](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect) to clear this up @liwadman, you can see the supported claims [here](https://token.actions.githubusercontent.com/.well-known/openid-configuration) which doesn't include custom claims to make the claim necessary for session tags as seen [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_adding-assume-role-idp)

It would be great if you could link to some of this documentation as well, as well as explaining why Github doesn't currently support session tags in the readme. I think this would lead to greatest clarity 🙂

2022-10-07 19:28 UTC, peterwoodworth commented on README.md
> +Note that for WebIdentity role assumption, the session tags have to be included in the encoded WebIdentity token.
Can you make sure to get rid of the extra space at the end of line 189

2023-02-22 00:45 UTC, kellertk commented
Closing this as stale. If you wish to reopen, please submit a new PR.

2023-02-22 00:45 UTC, closed without merging