feat: examples
aws-actions/configure-aws-credentials pull request #553
Opened 2022-10-26 03:30 UTC by grolston

*Issue #, if available:*

*Description of changes:*

Adds in example cloudformation templates and workflow templates for OIDC federation with IAM IdP setup. Example gives simple setup for either the OIDC IAM IdP setup only or creating the OIDC IAM IdP setup with a simple role. The role setup leverages specified GitHub Organization, Repository, and branch. The GitHub workflow example uses the OIDC role with managed policy to deploy a cloudformation template.
---

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/master/CONTRIBUTING.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-10-26 18:53 UTC, kellertk requested changes
Hi there! Thanks for the PR!

We definitely want to get some better examples for the action, but from experience customers will want to copy/paste examples if possible. I noticed we're referencing a `cloudformation/ec2-bastion.yml` file that's not present in the folder, so this isn't just a drop in and go example :)

Could we structure things this way instead?
```
examples/
    README.md
    <name of example1>/
        README.md
        cloudformation/
            <name of template>.yml
        workflows/
            <name of workflow>.yml
    <name of example2>/
        README.md
        cloudformation/
            <name of template>.yml
            <extra_file>.yml
        workflows/
            <name of workflow>.yml
    ...
```

That way each folder is a complete, self-contained example.

2022-10-28 22:36 UTC, grolston commented
Pushing latest restructuring for the examples directory.

2022-10-28 23:48 UTC, kellertk requested changes
Looks good! Just a few minor changes, please :)

2022-10-28 23:48 UTC, kellertk commented on examples/cfn-deploy-example/README.md
> +| AWS_ACCOUNT_ID | configure-aws-credential | The AWS account ID |
```suggestion
| AWS_ACCOUNT_ID | configure-aws-credentials | The AWS account ID |
```

2022-10-28 23:48 UTC, kellertk commented on examples/cfn-deploy-example/README.md
> +| AWS_DEPLOY_ROLE | configure-aws-credential | The name of the IAM role |
```suggestion
| AWS_DEPLOY_ROLE | configure-aws-credentials | The name of the IAM role |
```

2022-10-28 23:48 UTC, kellertk commented on examples/cfn-deploy-example/.github/workflows/compliance.yml
> +    - uses: actions/checkout@v2
```suggestion
    - uses: actions/checkout@v3
```

2022-10-28 23:48 UTC, kellertk commented on examples/cfn-deploy-example/.github/workflows/deploy.yml
> +      uses: aws-actions/configure-aws-credentials@v1
```suggestion
      uses: aws-actions/configure-aws-credentials@v1-node16
```

2022-10-29 14:32 UTC, grolston commented on examples/cfn-deploy-example/README.md
> +| AWS_ACCOUNT_ID | configure-aws-credential | The AWS account ID |
added fix

2022-10-29 14:32 UTC, grolston commented on examples/cfn-deploy-example/.github/workflows/compliance.yml
> +    - uses: actions/checkout@v2
changed version

2022-10-29 14:32 UTC, grolston commented on examples/cfn-deploy-example/README.md
> +| AWS_DEPLOY_ROLE | configure-aws-credential | The name of the IAM role |
added fix

2022-10-31 23:45 UTC, kellertk approved these changes

2022-10-31 23:47 UTC, merged