Remove warning about using long-term credentials
aws-actions/configure-aws-credentials pull request #926
Opened 2023-11-21 07:51 UTC by tim-finnigan

*Issue #, if available:* https://github.com/aws-actions/configure-aws-credentials/issues/885

*Description of changes:* https://github.com/aws-actions/configure-aws-credentials/pull/871 added a warning about using long-term credentials. Upon discussion with the team, we think that this should be called out in the README rather than in a warning. And there is already a recommendation in the README to use OIDC to get short-lived credentials:
>We recommend using [GitHub's OIDC provider](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to get short-lived AWS credentials needed for your actions.

Although long-term credentials may not be recommended in most cases, the AWS [IAM documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#rotate-credentials) does note:

>There are specific use cases that require long-term credentials with IAM users in AWS. 

Ultimately Identity and Access Management is the customer's responsibility in the [Shared Responsibility Model](https://aws.amazon.com/compliance/shared-responsibility-model/). We can recommend [best practices](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html) but should be cautious about adding warnings that may not be universally applicable. 

---

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/main/CONTRIBUTING.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-21 23:08 UTC, kellertk requested changes

2023-11-21 23:08 UTC, kellertk commented on README.md
> +**Update: this warning has been removed.**
We probably can just leave this out.

2023-11-21 23:08 UTC, kellertk commented on dist/index.js
This file is generated. Don't edit it.

2023-12-06 00:17 UTC, kellertk approved these changes

2023-12-06 00:23 UTC, merged

2024-01-12 16:58 UTC, haooliveira84 commented
@kellertk when this PR will be part of `v4`?