Update README to note requirement for self-hosted runners using v4
aws-actions/configure-aws-credentials pull request #941
Opened 2023-12-05 22:57 UTC by tim-finnigan

*Issue #, if available:* https://github.com/aws-actions/configure-aws-credentials/issues/920#issuecomment-1832694323

*Description of changes:* Update README to note requirement for self-hosted runners using v4

---

* [ x ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws-actions/configure-aws-credentials/blob/main/CONTRIBUTING.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-06 00:15 UTC, kellertk requested changes
I don't understand why the licenses got updated if you're only making a README change. Did you add THIRD-PARTY to your commit by mistake?

2023-12-06 00:15 UTC, kellertk commented on README.md
> +changed from `v3` is that the action now runs on `node20` instead of `node16`. If using a self-hosted runner, specify [v2.311.0](https://github.com/actions/runner/releases/tag/v2.311.0) or above for
No one will notice this when it's rendered (so don't change it) but the line wrapping doesn't match the other line wrappings.

2023-12-06 00:30 UTC, tim-finnigan commented
> I don't understand why the licenses got updated if you're only making a README change. Did you add THIRD-PARTY to your commit by mistake?

That file just updated after running `npm run package`. Should I undo any changes to that file?

2023-12-08 00:27 UTC, tim-finnigan commented
> I don't understand why the licenses got updated if you're only making a README change. Did you add THIRD-PARTY to your commit by mistake?

Reverted the license changes happened after packaging.

2024-01-02 23:24 UTC, kellertk approved these changes

2024-01-09 17:02 UTC, merged